os:
  - osx
before_install:
  - chmod a+x ./scripts/installUnityTravis.sh
  - chmod a+x ./scripts/runTestsTravis.sh
install:
  - ./scripts/installUnityTravis.sh
  - brew install python3
script:
  - ./scripts/runTestsTravis.sh
notifications:
  email:
    on_success: never
    on_failure: always
